version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db

  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    ports:
      - "8080:8080"
    environment:
      - JIRA_HOME=/var/atlassian/application-data/jira
      - JIRA_DB_TYPE=postgresql
      - JIRA_DB_HOST=db
      - JIRA_DB_PORT=5432
      - JIRA_DB_NAME=jiradb
      - JIRA_DB_USER=jiraeta
      - JIRA_DB_PASSWORD=jirasola
    volumes:
      - jira_data:/var/atlassian/application-data/jira
    depends_on:
      - db

  bitbucket:
    image: atlassian/bitbucket-server:latest
    container_name: bitbucket
    ports:
      - "7990:7990"
    environment:
      - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket
      - BITBUCKET_DB_HOST=db
      - BITBUCKET_DB_PORT=5432
      - BITBUCKET_DB_NAME=bitbucketdb
      - BITBUCKET_DB_USER=bitbucketeta
      - BITBUCKET_DB_PASSWORD=bitbucketsola
    volumes:
      - bitbucket_data:/var/atlassian/application-data/bitbucket
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      bash -c "
        docker-entrypoint.sh postgres &
        sleep 10 && 
        psql -U postgres -c \"CREATE DATABASE jiradb;\" && 
        psql -U postgres -c \"CREATE USER jiraeta WITH ENCRYPTED PASSWORD 'jirasola';\" && 
        psql -U postgres -c \"GRANT ALL PRIVILEGES ON DATABASE jiradb TO jiraeta;\" && 
        psql -U postgres -c \"CREATE DATABASE bitbucketdb;\" && 
        psql -U postgres -c \"CREATE USER bitbucketeta WITH ENCRYPTED PASSWORD 'bitbucketsola';\" && 
        psql -U postgres -c \"GRANT ALL PRIVILEGES ON DATABASE bitbucketdb TO bitbucketeta;\"
      "

volumes:
  jira_data:
  bitbucket_data:
  postgres_data:
